// pages/xingz/xingz.js
var that;
Page({
  data: {
    ww:'',
    hh:'',
    list:[
      {
        name:"白羊座",
        cn:"baiyang",
        url:"https://murenziwei.github.io/lwcs/8432807_1.jpg"
      },
      {
        name:"金牛座",
        cn:"jinniu",
        url:"https://murenziwei.github.io/lwcs/8432807_2.jpg"
      },
      {
        name:"双子座",
        cn:"shuangzi",
        url:"https://murenziwei.github.io/lwcs/8432807_3.jpg"
      },
      {
        name:"巨蟹座",
        cn:"juxie",
        url:"https://murenziwei.github.io/lwcs/8432807_4.jpg"
      },
      {
        name:"狮子座",
        cn:"shizi",
        url:"https://murenziwei.github.io/lwcs/8432807_5.jpg"
      },
      {
        name:"处女座",
        cn:"chunv",
        url:"https://murenziwei.github.io/lwcs/8432807_6.jpg"
      },
      {
        name:"天秤座",
        cn:"tiancheng",
        url:"https://murenziwei.github.io/lwcs/8432807_7.jpg"
      },
      {
        name:"天蝎座",
        cn:"tianxie",
        url:"https://murenziwei.github.io/lwcs/8432807_8.jpg"
      },
      {
        name:"射手座",
        cn:"sheshou",
        url:"https://murenziwei.github.io/lwcs/8432807_9.jpg"
      },
      {
        name:"摩羯座",
        cn:"mojie",
        url:"https://murenziwei.github.io/lwcs/8432807_10.jpg"
      },
      {
        name:"水瓶座",
        cn:"shuiping",
        url:"https://murenziwei.github.io/lwcs/8432807_11.jpg"
      },
      {
        name:"双鱼座",
        cn:"shuangyu",
        url:"https://murenziwei.github.io/lwcs/8432807_12.jpg"
      }
    ]
  },
  onLoad: function (options) {
    that=this;
    tt.getSystemInfo({
      success(res){
        console.log(res,"不得了");
        that.setData({
          ww:res.windowWidth,
          hh:res.windowHeight
        })
      }
    });
  }
})